### ISSUE TITLE
NullPointerException in EventBusPrometheusMetrics$Metric

### ISSUE THREAD

**Issue by girshfeld** [nolequen/vertx-prometheus-metrics#6]
Hi! There is NPE in EventBusPrometheusMetrics
```
июл 06, 2017 3:57:48 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException
	at io.vertx.ext.prometheus.metrics.EventBusPrometheusMetrics$Metric.access$000(EventBusPrometheusMetrics.java:119)
	at io.vertx.ext.prometheus.metrics.EventBusPrometheusMetrics.handlerUnregistered(EventBusPrometheusMetrics.java:54)
	at io.vertx.ext.prometheus.metrics.EventBusPrometheusMetrics.handlerUnregistered(EventBusPrometheusMetrics.java:13)
	at io.vertx.core.eventbus.impl.HandlerHolder.setRemoved(HandlerHolder.java:37)
	at io.vertx.core.eventbus.impl.EventBusImpl.removeLocalRegistration(EventBusImpl.java:289)
	at io.vertx.core.eventbus.impl.EventBusImpl.removeRegistration(EventBusImpl.java:268)
	at io.vertx.core.eventbus.impl.HandlerRegistration.doUnregister(HandlerRegistration.java:137)
	at io.vertx.core.eventbus.impl.HandlerRegistration.unregister(HandlerRegistration.java:113)
	at io.vertx.core.eventbus.impl.EventBusImpl.unregisterAll(EventBusImpl.java:486)
	at io.vertx.core.eventbus.impl.EventBusImpl.close(EventBusImpl.java:192)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.close(ClusteredEventBus.java:177)
	at io.vertx.core.impl.VertxImpl.lambda$null$8(VertxImpl.java:508)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by vkryuchenko** [comment]
And addition
`[06-07 15:56:03,340] vert.x-eventloop-thread-2 - io.vertx.core.impl.ContextImpl - ERROR : Unhandled exception
java.lang.IllegalArgumentException: Label cannot be null.
	at io.prometheus.client.SimpleCollector.labels(SimpleCollector.java:68)
	at io.vertx.ext.prometheus.metrics.counters.ConnectionGauge.gauge(ConnectionGauge.java:32)
	at io.vertx.ext.prometheus.metrics.counters.ConnectionGauge.connected(ConnectionGauge.java:19)
	at io.vertx.ext.prometheus.metrics.TCPPrometheusMetrics.connected(TCPPrometheusMetrics.java:27)
	at io.vertx.ext.prometheus.metrics.TCPPrometheusMetrics.connected(TCPPrometheusMetrics.java:12)
	at io.vertx.core.net.impl.NetClientImpl.lambda$connected$6(NetClientImpl.java:249)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
	at io.vertx.core.net.impl.NetClientImpl.connected(NetClientImpl.java:248)
	at io.vertx.core.net.impl.NetClientImpl.lambda$connect$5(NetClientImpl.java:220)
	at io.vertx.core.net.impl.ChannelProvider.lambda$connect$0(ChannelProvider.java:40)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:306)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:630)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)`
